version: '3.3'
services:

  database:
    image: sameersbn/postgresql:latest
    container_name: nodejs-nights-db
    environment:
      - DB_NAME=nodejs-nights-local,nodejs-nights-test
      - PG_TRUST_LOCALNET=true
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: nodejs-nights-redis
    ports:
      - "6379:6379"
